spring.datasource.url=jdbc:postgresql://localhost:5432/payflow_db
spring.datasource.username=postgres
spring.datasource.password=newpassword
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql= true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=qwertyuhjgfdeuekaweevfreghergfekhhgejgfewjgfghgjdheggheg
jwt.expiration=86400000